// flow-typed signature: 233de3ca7461ea3df1e2a7229304cb62
// flow-typed version: <<STUB>>/peachapisec_v1.5.28/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'peachapisec'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'peachapisec' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'peachapisec/peacherror' {
  declare module.exports: any;
}

declare module 'peachapisec/test/peachapisec.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'peachapisec/index' {
  declare module.exports: $Exports<'peachapisec'>;
}
declare module 'peachapisec/index.js' {
  declare module.exports: $Exports<'peachapisec'>;
}
declare module 'peachapisec/peacherror.js' {
  declare module.exports: $Exports<'peachapisec/peacherror'>;
}
declare module 'peachapisec/test/peachapisec.test.js' {
  declare module.exports: $Exports<'peachapisec/test/peachapisec.test'>;
}
